[project]
name = "accessagent"
version = "0.1.0"
description = "An ai agent that assesses accessibility for a website URL"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "axe-core-python>=0.1.0",
    "langchain-anthropic>=1.6.1",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.0",
    "langgraph>=1.2.11",
    "playwright>=1.62.0",
    "pytest>=9.1.1",
    "streamlit>=1.62.0",
]
